environment:
  PYTHON: "C:\\Python35"
  PYTHON_VERSION: 3.5
  PYTHON_ARCH: "32"

init:
  - "ECHO %PYTHON% %PYTHON_VERSION% %PYTHON_ARCH%"

install:
  - "SET PATH=%PYTHON%;%PYTHON%\\Scripts;%PATH%"
  - "python -m pip install -U pip setuptools"
  - "pip install -r requirements-dev.txt -r requirements.txt"
  - "pip install nuitka"

test_script:
  - "pip install -e ."


after_test:
  - "mkdir svtplay-dl"
  - "mkdir svtplay-dl\\certifi"
  - "nuitka --recurse-all --output svtplay-dl bin/svtplay-dl"
  - "copy %PYTHON%\\lib\\site-packages\\certifi\\cacert.pem svtplay-dl\\certifi"
  - "dir svtplay-dl"
  - "svtplay-dl\\svtplay-dl.exe --version"
  - "rmdir /q /s svtplay-dl\\svtplay-dl.build"
  - "7z.exe a -tzip svtplay-dl.zip svtplay-dl"

artifacts:
  - path: svtplay-dl.zip
    name: svtplay-dl

build: off